- hosts: production 
  remote_user: user
  vars:
    app_name: {{ project_name }} 
    github_user: {{ project_name }}
    server_name: 0.0.0.0
    deploy_user: user 
  roles:
     - { role: ortelius.geonode }
